options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--build-arg',
           'VITE_REACT_APP_FIREBASE_API_KEY=$_VITE_REACT_APP_FIREBASE_API_KEY',
           '--build-arg',
           'VITE_REACT_APP_FIREBASE_AUTH_DOMAIN=$_VITE_REACT_APP_FIREBASE_AUTH_DOMAIN',
           '--build-arg',
           'VITE_REACT_APP_DATABASE_URL=$_VITE_REACT_APP_DATABASE_URL',
           '--build-arg',
           'VITE_REACT_APP_FIREBASE_PROJECT_ID=$_VITE_REACT_APP_FIREBASE_PROJECT_ID',
           '--build-arg',
           'VITE_REACT_APP_FIREBASE_STORAGE_BUCKET=$_VITE_REACT_APP_FIREBASE_STORAGE_BUCKET',
           '--build-arg',
           'VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$_VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID',
           '--build-arg',
           'VITE_REACT_APP_FIREBASE_APP_ID=$_VITE_REACT_APP_FIREBASE_APP_ID',
           '--build-arg',
           'VITE_REACT_APP_BACKEND_URL=$_VITE_REACT_APP_BACKEND_URL',
           '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA',
           '-f', 'linguists-and-readers-web/Dockerfile', 'linguists-and-readers-web']


  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'frontend',
           '--image', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA',
           '--platform', 'managed',
           '--region', 'europe-west1',
            '--allow-unauthenticated']

# Step 4: Add a timeout of 5 minutes
timeout: '600s'

# Step 5: Specify images to be used
images:
  - 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'