options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA', '-f', 'linguists-and-readers-backend/Dockerfile', 'linguists-and-readers-backend']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA']

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'backend',
           '--image', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA',
           '--platform', 'managed',
           '--region', 'europe-west1',
           '--allow-unauthenticated',
    ]

# Step 4: Add a timeout of 5 minutes
timeout: '300s'

# Step 5: Specify images to be used
images:
  - 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA'